apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        memory: "5Gi"
        cpu: "4"
    command: ["sleep", "3600"] 
